spring.datasource.url=jdbc:postgresql://localhost:5432/springlock
spring.datasource.username=springlock
spring.datasource.password=springlock
spring.datasource.driver-class-name=org.postgresql.Driver

